FROM node:16-alpine

WORKDIR /app

# Install backend dependencies
COPY package*.json ./
RUN npm install --production

# Copy backend source code and upload folders
COPY backend/ ./backend/
COPY uploads/ ./uploads/

# Expose backend port
EXPOSE 5000

# Start backend server
CMD ["npm", "start"]
